DATAFILE='/data/input.txt'
STATNUMB=8
SAMPLESIZE=500
TRUNCATION=500
NUM_RESTARTS=5
NUM_ITER_RESTARTS=100
NUM_ITER_FINAL=100
EPSILON=10e-6
TOLERANCE=10e-8
TAU_STAT=10e-4
TAU_OBVS=10e-4

rm ./output/*

java -cp .:mallet.jar:trove-2.0.2.jar:gson-2.3.jar inference \
$DATAFILE \
$STATNUMB \
$SAMPLESIZE \
$TRUNCATION \
$NUM_RESTARTS \
$NUM_ITER_RESTARTS \
$NUM_ITER_FINAL \
$EPSILON \
$TOLERANCE \
$TAU_STAT \
$TAU_OBVS

cp output/global* /data/
